#!/usr/bin/env bun

import { avroToTypeScript, type RecordType } from 'avro-typescript'

const [input]: Partial<string[]> = Bun.argv.slice(2);

if (!input) {
  console.error('Invalid usage: usage: bun run avro:gentypes <input>');
  process.exit(1);
}

const schemaJson = await Bun.file(input).json() as RecordType;
console.log(avroToTypeScript(schemaJson));